# Evaluación de la velocidad de R

In [1]:
library(readr)

# Crear un dataframe desde un archivo csv

In [2]:
df <- read_csv("2008.csv")


-- Column specification ------------------------------------------------------------------------------------------------
cols(
  .default = col_double(),
  UniqueCarrier = col_character(),
  TailNum = col_character(),
  Origin = col_character(),
  Dest = col_character(),
  CancellationCode = col_character()
)
i Use `spec()` for the full column specifications.




In [7]:
str(df)

spec_tbl_df [7,009,728 x 29] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Year             : num [1:7009728] 2008 2008 2008 2008 2008 ...
 $ Month            : num [1:7009728] 1 1 1 1 1 1 1 1 1 1 ...
 $ DayofMonth       : num [1:7009728] 3 3 3 3 3 3 3 3 3 3 ...
 $ DayOfWeek        : num [1:7009728] 4 4 4 4 4 4 4 4 4 4 ...
 $ DepTime          : num [1:7009728] 2003 754 628 926 1829 ...
 $ CRSDepTime       : num [1:7009728] 1955 735 620 930 1755 ...
 $ ArrTime          : num [1:7009728] 2211 1002 804 1054 1959 ...
 $ CRSArrTime       : num [1:7009728] 2225 1000 750 1100 1925 ...
 $ UniqueCarrier    : chr [1:7009728] "WN" "WN" "WN" "WN" ...
 $ FlightNum        : num [1:7009728] 335 3231 448 1746 3920 ...
 $ TailNum          : chr [1:7009728] "N712SW" "N772SW" "N428WN" "N612SW" ...
 $ ActualElapsedTime: num [1:7009728] 128 128 96 88 90 101 240 233 95 79 ...
 $ CRSElapsedTime   : num [1:7009728] 150 145 90 90 90 115 250 250 95 95 ...
 $ AirTime          : num [1:7009728] 116 113 76 78 77 87 2

In [3]:
#Cantidad de filas
nrow(df)

[1] 7009728

In [4]:
#Cantidad de columnas
ncol(df)

[1] 29

## Selección de columnas a mostrar en un dataframe

In [5]:
head(df[c("DepTime","CRSDepTime","ArrTime")],5)

DepTime CRSDepTime ArrTime
1 2003    1955       2211   
2  754     735       1002   
3  628     620        804   
4  926     930       1054   
5 1829    1755       1959

In [8]:
#Muestra una columna del dataframe
head(df$ArrDelay,15)

[1] -14   2  14  -6  34  11  57 -18   2 -16   1  80   1  10  -4

In [ ]:
nrow(delay)

# Cálculo del tiempo

In [9]:
delay <- df$ArrDelay
#Filtra los datos que no sean NA y sobre escribe el dataframe con los nuevos resultados
delay <- delay[!is.na(delay)]

In [10]:
#Evalua cuanto se tardó en calcular la media
start <- Sys.time()
mean(delay)
print(Sys.time() -start)

[1] 8.168452

Time difference of 0.02095103 secs


In [11]:
#devuelve una tabla resumen
system.time(mean(delay))

   user  system elapsed 
   0.02    0.00    0.02 

In [ ]:
#Aproximación más avanzada a evaluación de tiempo se logra con
library("rbenchmark")

In [ ]:
benchmark(
    "Media funcion"={
        mean(delay)
    },
    "Media con funciones"={
        sum(delay)/length(delay)
    },
    "Media manual"={
        media <- 0
        for(i in 1:length(delay)){
            media <- media + delay[i]
        }
        media/length(delay)
    },
    replications = 20,
    columns = c("test","replications","elapsed","relative")
)

In [ ]:
for(i in 1:10){
    print(i)
}

# Importar un archivo de excel

In [46]:
library(readxl)

Warning message:
"package 'readxl' was built under R version 4.1.2"


In [47]:
M <- read_excel("C:/Users/ordonez/Documents/SAP/SAP GUI/M.XLSX", col_types = c("text", 
"text", "numeric", "numeric", "numeric", 
"numeric", "text", "text", "text", "text", 
"text", "numeric", "text", "text", "text", 
"text", "numeric", "text", "date", "text", 
"numeric", "text", "numeric"))

In [48]:
View(M)

Material UMB Libre utiliz. Punto pedido Stock máximo Tam.lote fijo CaP
1     1011796  C/U     0.00          50.0          0       120           ND 
2     1033865  C/U     0.00           0.0          0         2           ND 
3     1000007  KG   7100.00           0.0       5000         0           ND 
4     1000008  KG  15222.72           0.0     240000         0           P5 
5     1000009  KG  33395.60           0.0          0         0           P8 
6     1000010  KG  10000.00       21648.5          0         0           Z6 
7     1000011  KG    900.00         450.0        900         0           VB 
8     1000012  KG     50.00        1000.0       8000         0           VB 
9     1000014  KG   6800.00        1983.0          0         0           Z6 
10    1000015  KG  85248.00           0.0     130000         0           P5 
11    1000017  KG    600.00           0.0          0         0           ND 
12    1000019  KG    500.00           0.0          0         0           P8 
13    1000020  KG   4994.00           0.0          0         0           P8 
14    1000021  KG  19584.00           0.0          0         0           P8 
15    1000022  KG      0.00        1000.0       2000         0           VB 
16    1000023  KG      0.00        1000.0       2000         0           VB 
17    1000024  KG  42696.00           0.0          0         0           P8 
18    1000027  KG   8100.00           0.0          0         0           P8 
19    1000028  KG  37584.00           0.0          0         0           P8 
20    1000031  KG  19880.00        1000.0       2000         0           VB 
21    1000033  L    6750.00           0.0          0         0           P8 
22    1000050  KG  51000.00      480000.0     480000         0           VB 
23    1000052  KG  19200.00      145000.0     145000         0           VB 
24    1000054  KG   1200.00         600.0       1200         0           VB 
25    1000055  KG   4200.00        3000.0       4500         0           VB 
26    1000056  KG   2000.00        4100.0       6000         0           VB 
27    1000057  KG  57460.00      480000.0     480000         0           VB 
28    1000058  L   56200.00      150000.0     190000         0           VB 
29    1000059  KG      0.00      120000.0     300000         0           VB 
30    1000060  KG   6120.00        4000.0       6000         0           VB 
...   ...      ... ...           ...          ...          ...           ...
28929 1063619  C/U 0                 0            0        0             PD 
28930 1063620  C/U 0                 0            0        0             PD 
28931 1063622  C/U 0                 0            0        0             PD 
28932 1063623  C/U 0                 0            0        0             PD 
28933 1063624  C/U 0                 0            0        0             PD 
28934 1063625  C/U 0                 0            0        0             PD 
28935 1063626  C/U 0                 0            0        0             PD 
28936 1063627  C/U 0                 0            0        0             PD 
28937 1063628  C/U 0                 0            0        0             PD 
28938 1006523  C/U 0                 0            0        0             PD 
28939 1006208  C/U 0                 2            3        0             V1 
28940 1063635  C/U 0                58           58        0             V1 
28941 1063640  C/U 0                 2            2        0             V1 
28942 1063641  C/U 0                 1            1        0             V1 
28943 1063642  C/U 0                 1            1        0             V1 
28944 1063643  C/U 0                 1            1        0             V1 
28945 1063644  C/U 0                 1            1        0             V1 
28946 1063645  C/U 0                 1            1        0             V1 
28947 1063646  C/U 0                 1            1        0             V1 
28948 1063547  C/U 0                 1            1        0             V1 
28

In [ ]:
M$Material

In [ ]:
M["Material"]

In [ ]:
M[1:10,c("Material","Texto breve de material")]

# Vectores

In [14]:
num <- c(3,5,4,7,8,2,9)
num

[1] 3 5 4 7 8 2 9

In [3]:
class(num)

[1] "numeric"

In [4]:
num[1]

[1] 3

In [5]:
num[2:4]

[1] 5 4 7

In [6]:
vec = 1:20

In [7]:
vec

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [15]:
numeros <- c(1,2,"tres")
numeros

[1] "1"    "2"    "tres"

# Matriz

In [16]:
matriz <- matrix(1:25, ncol=5)
matriz

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [17]:
matriz2 = matrix(1:25, ncol=5, byrow=TRUE)
matriz2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [18]:
matriz <- matrix(data=1:20,nrow = 4,ncol=5,byrow = FALSE)
matriz

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [19]:
matriz[2,3]

[1] 10

In [20]:
matriz[,2] #recupera la columna 2

[1] 5 6 7 8

In [21]:
matriz[,-c(4,5)] #matriz sin las columnas 4 y 5

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

# Arreglos es una matrices de varias dimensiones

In [22]:
arreglo <- array(data = letters[1:24],dim = c(3,4,2))
arreglo

, , 1

     [,1] [,2] [,3] [,4]
[1,] "a"  "d"  "g"  "j" 
[2,] "b"  "e"  "h"  "k" 
[3,] "c"  "f"  "i"  "l" 

, , 2

     [,1] [,2] [,3] [,4]
[1,] "m"  "p"  "s"  "v" 
[2,] "n"  "q"  "t"  "w" 
[3,] "o"  "r"  "u"  "x"

In [23]:
arreglo[,,1]

[,1] [,2] [,3] [,4]
[1,] a    d    g    j   
[2,] b    e    h    k   
[3,] c    f    i    l

# Data frame

In [24]:
#data frame

edad <- c(15, 19, 13, NA, 20)
deporte <- c(TRUE, TRUE, NA, FALSE, TRUE)
comic_fav <- c(NA, 'Superman', 'Batman', NA, 'Batman')

In [25]:
df <- data.frame(edad,deporte,comic_fav)
df

edad deporte comic_fav
1 15    TRUE   NA       
2 19    TRUE   Superman 
3 13      NA   Batman   
4 NA   FALSE   NA       
5 20    TRUE   Batman

In [26]:
df$edad

[1] 15 19 13 NA 20

In [27]:
df[,1]

[1] 15 19 13 NA 20

In [28]:
df[["deporte"]] #devuelve en forma de vetor

[1]  TRUE  TRUE    NA FALSE  TRUE

In [29]:
df["deporte"] #devuelve en forma de data frame

deporte
1  TRUE  
2  TRUE  
3    NA  
4 FALSE  
5  TRUE

In [30]:
str(df[["comic_fav"]])

 chr [1:5] NA "Superman" "Batman" NA "Batman"


In [31]:
str(df["comic_fav"])

'data.frame':	5 obs. of  1 variable:
 $ comic_fav: chr  NA "Superman" "Batman" NA ...


In [32]:
df[c("deporte","edad")]

deporte edad
1  TRUE   15  
2  TRUE   19  
3    NA   13  
4 FALSE   NA  
5  TRUE   20

In [33]:
df[2:4,1] #recuperar edad de las posiciones 3 a 4

[1] 19 13 NA

In [34]:
#Extraer subconjunto de un data frame

subset(df,subset=deporte==TRUE)

edad deporte comic_fav
1 15   TRUE    NA       
2 19   TRUE    Superman 
5 20   TRUE    Batman

In [35]:
subset(df,subset = edad < 20)

edad deporte comic_fav
1 15   TRUE    NA       
2 19   TRUE    Superman 
3 13     NA    Batman

In [36]:
subset(df,subset = edad < 20 & deporte==TRUE)

edad deporte comic_fav
1 15   TRUE    NA       
2 19   TRUE    Superman

In [37]:
url <- 'https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo'

In [38]:
df1 <- read.table(url,header=T)
df1

edad peso altura sexo   muneca biceps
1  43   87.3 188.0  Hombre 12.2   35.8  
2  65   80.0 174.0  Hombre 12.0   35.0  
3  45   82.3 176.5  Hombre 11.2   38.5  
4  37   73.6 180.3  Hombre 11.2   32.2  
5  55   74.1 167.6  Hombre 11.8   32.9  
6  33   85.9 188.0  Hombre 12.4   38.5  
7  25   73.2 180.3  Hombre 10.6   38.3  
8  35   76.3 167.6  Hombre 11.3   35.0  
9  28   65.9 183.0  Hombre 10.2   32.1  
10 26   90.9 183.0  Hombre 12.0   40.4  
11 43   89.1 179.1  Hombre 11.3   36.5  
12 30   62.3 170.2  Hombre 11.5   34.2  
13 26   82.7 177.8  Hombre 11.5   35.2  
14 51   79.1 179.1  Hombre 11.8   34.0  
15 30   98.2 190.5  Hombre 10.7   34.8  
16 24   84.1 177.8  Hombre 11.5   38.6  
17 35   83.2 180.3  Hombre 11.1   36.4  
18 37   83.2 180.3  Hombre 10.5   34.0  
19 22   51.6 161.2  Mujer   9.2   24.3  
20 20   59.0 167.5  Mujer   9.9   27.8  
21 19   49.2 159.5  Mujer   8.9   24.0  
22 25   63.0 157.0  Mujer   9.5   28.0  
23 21   53.6 155.8  Mujer   9.1   26.9  
24 23   59.0 170.0  Mujer  10.0   26.5  
25 26   47.6 159.1  Mujer   9.4   24.1  
26 22   69.8 166.0  Mujer  10.7   29.2  
27 28   66.8 176.2  Mujer   9.8   29.0  
28 40   75.2 160.2  Mujer  11.5   33.6  
29 32   55.2 172.5  Mujer   8.6   24.8  
30 25   54.2 170.9  Mujer   9.7   25.4  
31 25   62.5 172.9  Mujer   9.2   25.9  
32 29   42.0 153.4  Mujer   8.3   24.0  
33 22   50.0 160.0  Mujer   8.6   25.6  
34 25   49.8 147.2  Mujer   9.0   26.0  
35 23   49.2 168.2  Mujer   9.6   23.5  
36 37   73.2 175.0  Mujer  11.0   31.0

In [39]:
dim(df1) #para conocer la dimensión original

[1] 36  6

In [40]:
subset(df1,subset = peso>80.0 & altura>185.0)

edad peso altura sexo   muneca biceps
1  43   87.3 188.0  Hombre 12.2   35.8  
6  33   85.9 188.0  Hombre 12.4   38.5  
15 30   98.2 190.5  Hombre 10.7   34.8

In [42]:
media <- mean(df1$peso)
subset(df1,subset = peso<media,select = c('peso','altura','sexo'))

peso altura sexo  
9  65.9 183.0  Hombre
12 62.3 170.2  Hombre
19 51.6 161.2  Mujer 
20 59.0 167.5  Mujer 
21 49.2 159.5  Mujer 
22 63.0 157.0  Mujer 
23 53.6 155.8  Mujer 
24 59.0 170.0  Mujer 
25 47.6 159.1  Mujer 
27 66.8 176.2  Mujer 
29 55.2 172.5  Mujer 
30 54.2 170.9  Mujer 
31 62.5 172.9  Mujer 
32 42.0 153.4  Mujer 
33 50.0 160.0  Mujer 
34 49.8 147.2  Mujer 
35 49.2 168.2  Mujer

# Lista "El objeto más flexible de R"

In [43]:
lista <- list()

In [44]:
class(lista)

[1] "list"

In [49]:
lista$objeto1 <- 1:25
lista$objeto2 <- "Alejandro"
lista$objeto3 <- M[1:4,c("Material","Texto breve de material")]

In [50]:
lista

$objeto1
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

$objeto2
[1] "Alejandro"

$objeto3
# A tibble: 4 x 2
  Material `Texto breve de material`                  
  <chr>    <chr>                                      
1 1011796  "LAMPARA BAJO CONSUMO 85W ROSCA E40 220V"  
2 1033865  "JUNTA SELLANTE GORE TEX DE 3/4\" x 9,14 M"
3 1000007  "BACTERICIDA BUSSAN 881"                   
4 1000008  "CAL HIDRATADA. ENV. 1000 KG."

In [51]:
lista$objeto1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

In [52]:
lista$objeto1[3:5]

[1] 3 4 5

# Usando la consola

In [ ]:
#Ejecutar dos expresiones en una línea
a = 3 ; b = 5

In [54]:
nombre <- readline(prompt="Ingrese su nombre: ")

Ingrese su nombre: ale


In [55]:
nombre

[1] "ale"

In [56]:
edad <- as.integer(readline(prompt="Ingrese su edad:"))

Ingrese su edad:47


In [58]:
class(edad)

[1] "integer"

# Funciones
* which.min: nos entrega la posición en donde está el valor mínimo del vector.<br>
* which.max: nos da la posición del valor máximo del vector.
* rev: invierte un vector.
* sin, cos, tan, asin, acos, atan, atan2, log, logb, log10, exp, sqrt, abs

In [63]:
angulos <- c(0, pi/2, pi)
sin(angulos)

[1] 0.000000e+00 1.000000e+00 1.224606e-16

In [64]:
logb(125, base=5)

[1] 3

# Función seq

In [66]:
seq(from=0, to=1, length.out = 11)

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

In [67]:
seq(from=1, to=9, by=2)

[1] 1 3 5 7 9

In [68]:
2:8

[1] 2 3 4 5 6 7 8

In [69]:
3:-5

[1]  3  2  1  0 -1 -2 -3 -4 -5

In [70]:
pi:6  # real sequence

[1] 3.141593 4.141593 5.141593

In [71]:
6:pi  # integer sequence

[1] 6 5 4

# Función rep

In [72]:
rep(x=1:4, times=2)

[1] 1 2 3 4 1 2 3 4

In [74]:
rep(x=1:4, times=c(2,3,2,2))

[1] 1 1 2 2 2 3 3 4 4

In [75]:
rep(x=1:4, each=2)

[1] 1 1 2 2 3 3 4 4

# Funciones round, ceiling, floor y trunc
* round(x, digits): sirve para redondear un número según los dígitos indicados.
* ceiling(x): entrega el mínimo entero mayor o igual que x.
* floor(x): entrega el máximo entero menor o igual que x.
* trunc(x): entrega la parte entera de un número x.

In [76]:
x <- 5.34896  # Número positivo elegido
round(x, digits=3)

[1] 5.349

In [77]:
ceiling(x)

[1] 6

In [78]:
floor(x)

[1] 5

In [79]:
trunc(x)

[1] 5

# sort y rank

In [80]:
x <- c(2, 3, 6, 4, 9, 5)
sort(x)

[1] 2 3 4 5 6 9

In [81]:
rank(x)

[1] 1 2 5 3 6 4

In [82]:
sort(x, decreasing=TRUE)

[1] 9 6 5 4 3 2

In [ ]:
#https://fhernanb.github.io/Manual-de-R/bucles.html